FROM node:20-alpine as build
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
# Copy custom nginx config
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80